export const ORG_MODULE_OPTIONS_TOKEN = 'ORG_MODULE_OPTIONS_TOKEN';
export const ORG_MODULE_SETTINGS_TOKEN = 'ORG_MODULE_SETTINGS_TOKEN';
export const ORG_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ORG_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ORG_MODULE_OWNER_LOOKUP_SERVICE =
  'ORG_MODULE_OWNER_LOOKUP_SERVICE';
export const ORG_MODULE_ORG_ENTITY_KEY = 'org';
