export const ORG_MODULE_SETTINGS_TOKEN = 'ORG_MODULE_SETTINGS_TOKEN';
export const ORG_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ORG_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ORG_MODULE_OWNER_LOOKUP_SERVICE_TOKEN =
  'ORG_MODULE_OWNER_LOOKUP_SERVICE_TOKEN';
export const ORG_MODULE_ORG_ENTITY_KEY = 'org';
export const ORG_MODULE_ORG_MEMBER_ENTITY_KEY = 'orgMember';
