export const ORG_MODULE_SETTINGS_TOKEN = 'ORG_MODULE_SETTINGS_TOKEN';
export const ORG_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ORG_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ORG_MODULE_OWNER_MODEL_SERVICE_TOKEN =
  'ORG_MODULE_OWNER_MODEL_SERVICE_TOKEN';
export const ORG_MODULE_CONFIGURABLE_CRUD_SERVICE_TOKEN = Symbol(
  '__ORG_MODULE_CONFIGURABLE_CRUD_SERVICE_TOKEN__',
);
export const ORG_MODULE_CONFIGURABLE_CRUD_PROFILE_SERVICE_TOKEN = Symbol(
  '__ORG_MODULE_CONFIGURABLE_CRUD_PROFILE_SERVICE_TOKEN__',
);
export const ORG_MODULE_ORG_ENTITY_KEY = 'org';
export const ORG_MODULE_ORG_MEMBER_ENTITY_KEY = 'org-member';
export const ORG_MODULE_ORG_PROFILE_ENTITY_KEY = 'org-profile';
