export const AUTHENTICATION_MODULE_OPTIONS_TOKEN =
  'AUTHENTICATION_MODULE_OPTIONS_TOKEN';

export const AUTHENTICATION_MODULE_SETTINGS_TOKEN =
  'AUTHENTICATION_MODULE_SETTINGS_TOKEN';

export const AUTHENTICATION_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTHENTICATION_MODULE_DEFAULT_SETTINGS_TOKEN';
