export const AUTHENTICATION_MODULE_SETTINGS_TOKEN =
  'AUTHENTICATION_MODULE_SETTINGS_TOKEN';

export const AUTHENTICATION_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTHENTICATION_MODULE_DEFAULT_SETTINGS_TOKEN';

export const ValidateTokenService = Symbol(
  '__AUTHENTICATION_MODULE_VALIDATE_TOKEN_SERVICE_TOKEN__',
);

export const AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN =
  'AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN';
