export const AUTH_VERIFY_MODULE_SETTINGS_TOKEN =
  'AUTH_VERIFY_MODULE_SETTINGS_TOKEN';

export const AUTH_VERIFY_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_VERIFY_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_VERIFY_MODULE_ENTITY_MANAGER_PROXY_TOKEN =
  'AUTH_VERIFY_MODULE_ENTITY_MANAGER_PROXY_TOKEN';

export const AuthVerifyOtpService = Symbol(
  '__AUTH_VERIFY_MODULE_OTP_SERVICE_TOKEN__',
);

export const AuthVerifyEmailService = Symbol(
  '__AUTH_VERIFY_MODULE_EMAIL_SERVICE_TOKEN__',
);

export const AuthVerifyUserLookupService = Symbol(
  '__AUTH_VERIFY_MODULE_USER_LOOKUP_SERVICE_TOKEN__',
);

export const AuthVerifyUserMutateService = Symbol(
  '__AUTH_VERIFY_MODULE_USER_MUTATE_SERVICE_TOKEN__',
);
