export const AUTH_VERIFY_MODULE_SETTINGS_TOKEN =
  'AUTH_VERIFY_MODULE_SETTINGS_TOKEN';

export const AUTH_VERIFY_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_VERIFY_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AuthVerifyOtpService = Symbol(
  '__AUTH_VERIFY_MODULE_OTP_SERVICE_TOKEN__',
);

export const AuthVerifyEmailService = Symbol(
  '__AUTH_VERIFY_MODULE_EMAIL_SERVICE_TOKEN__',
);

export const AuthVerifyUserModelService = Symbol(
  '__AUTH_VERIFY_MODULE_USER_MODEL_SERVICE_TOKEN__',
);
