export const REFERENCE_ID_NO_MATCH = 'REFERENCE_ID_NO_MATCH';
export const REFERENCE_LOOKUP_ERROR = 'REFERENCE_LOOKUP_ERROR';
export const REFERENCE_MUTATE_ERROR = 'REFERENCE_MUTATE_ERROR';
export const REFERENCE_VALIDATION_ERROR = 'REFERENCE_VALIDATION_ERROR';