export const AUTH_GITHUB_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_GITHUB_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_GITHUB_MODULE_OPTIONS_TOKEN =
  'AUTH_GITHUB_MODULE_OPTIONS_TOKEN';

export const AUTH_GITHUB_MODULE_SETTINGS_TOKEN =
  'AUTH_GITHUB_MODULE_SETTINGS_TOKEN';

export const AUTH_GITHUB_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_GITHUB_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_GITHUB_STRATEGY_NAME = 'github';
