export const GITHUB_ISSUE_TOKEN_SERVICE_TOKEN =
  'GITHUB_ISSUE_TOKEN_SERVICE_TOKEN';

export const GITHUB_MODULE_OPTIONS_TOKEN = 'GITHUB_MODULE_OPTIONS_TOKEN';

export const GITHUB_MODULE_SETTINGS_TOKEN = 'GITHUB_MODULE_SETTINGS_TOKEN';

export const GITHUB_MODULE_DEFAULT_SETTINGS_TOKEN =
  'GITHUB_MODULE_DEFAULT_SETTINGS_TOKEN';

export const GITHUB_STRATEGY_NAME = 'github';
