export const AUTH_RECOVERY_MODULE_SETTINGS_TOKEN =
  'AUTH_RECOVERY_MODULE_SETTINGS_TOKEN';

export const AUTH_RECOVERY_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_RECOVERY_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AuthRecoveryOtpService = Symbol(
  '__AUTH_RECOVERY_MODULE_OTP_SERVICE_TOKEN__',
);

export const AuthRecoveryEmailService = Symbol(
  '__AUTH_RECOVERY_MODULE_EMAIL_SERVICE_TOKEN__',
);

export const AuthRecoveryUserLookupService = Symbol(
  '__AUTH_RECOVERY_MODULE_USER_LOOKUP_SERVICE_TOKEN__',
);

export const AuthRecoveryUserMutateService = Symbol(
  '__AUTH_RECOVERY_MODULE_USER_MUTATE_SERVICE_TOKEN__',
);

export const AUTH_RECOVERY_MODULE_ENTITY_MANAGER_PROXY_TOKEN =
  'AUTH_RECOVERY_MODULE_ENTITY_MANAGER_PROXY_TOKEN';
