export const AUTH_RECOVERY_MODULE_OPTIONS_TOKEN =
  'AUTH_RECOVERY_MODULE_OPTIONS_TOKEN';

export const AUTH_RECOVERY_MODULE_SETTINGS_TOKEN =
  'AUTH_RECOVERY_MODULE_SETTINGS_TOKEN';

export const AUTH_RECOVERY_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_RECOVERY_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_RECOVERY_SERVICE_TOKEN = 'AUTH_RECOVERY_SERVICE_TOKEN';

export const AUTH_RECOVERY_OTP_SERVICE_TOKEN =
  'AUTH_RECOVERY_OTP_SERVICE_TOKEN';

export const AUTH_RECOVERY_EMAIL_SERVICE_TOKEN =
  'AUTH_RECOVERY_EMAIL_SERVICE_TOKEN';

export const AUTH_RECOVERY_USER_LOOKUP_SERVICE_TOKEN =
  'AUTH_RECOVERY_USER_LOOKUP_SERVICE_TOKEN';

export const AUTH_RECOVERY_USER_MUTATED_SERVICE_TOKEN =
  'AUTH_RECOVERY_USER_MUTATED_SERVICE_TOKEN';

export const AUTH_RECOVERY_STRATEGY_NAME = 'auth_recovery';
