export const AUTH_LOCAL_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_LOCAL_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_LOCAL_MODULE_OPTIONS_TOKEN =
  'AUTH_LOCAL_MODULE_OPTIONS_TOKEN';

export const AUTH_LOCAL_MODULE_SETTINGS_TOKEN =
  'AUTH_LOCAL_MODULE_SETTINGS_TOKEN';

export const AUTH_LOCAL_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_LOCAL_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_LOCAL_STRATEGY_NAME = 'local';
