export const AUTH_LOCAL_MODULE_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_LOCAL_MODULE_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_LOCAL_MODULE_VALIDATE_USER_SERVICE_TOKEN =
  'AUTH_LOCAL_MODULE_VALIDATE_USER_SERVICE_TOKEN';

export const AUTH_LOCAL_MODULE_SETTINGS_TOKEN =
  'AUTH_LOCAL_MODULE_SETTINGS_TOKEN';

export const AUTH_LOCAL_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_LOCAL_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_LOCAL_MODULE_USER_LOOKUP_SERVICE_TOKEN =
  'AUTH_LOCAL_MODULE_USER_LOOKUP_SERVICE_TOKEN';

export const AUTH_LOCAL_MODULE_PASSWORD_VALIDATION_SERVICE_TOKEN =
  'AUTH_LOCAL_MODULE_PASSWORD_VALIDATION_SERVICE_TOKEN';

export const AUTH_LOCAL_STRATEGY_NAME = 'local';

export const AUTH_LOCAL_AUTHENTICATION_TYPE = 'auth-local';
