export const CACHE_MODULE_SETTINGS_TOKEN = 'CACHE_MODULE_SETTINGS_TOKEN';
export const CACHE_MODULE_REPOSITORIES_TOKEN =
  'CACHE_MODULE_REPOSITORIES_TOKEN';
export const CACHE_MODULE_CRUD_SERVICES_TOKEN =
  'CACHE_MODULE_CRUD_SERVICES_TOKEN';
export const CACHE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'CACHE_MODULE_DEFAULT_SETTINGS_TOKEN';
export const CACHE_MODULE_CACHE_ENTITY_KEY = 'cache';
