export const AUTH_HISTORY_MODULE_OPTIONS_TOKEN =
  'AUTH_HISTORY_MODULE_OPTIONS_TOKEN';
export const AUTH_HISTORY_MODULE_SETTINGS_TOKEN =
  'AUTH_HISTORY_MODULE_SETTINGS_TOKEN';
export const AUTH_HISTORY_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_HISTORY_MODULE_DEFAULT_SETTINGS_TOKEN';
export const AUTH_HISTORY_MODULE_AUTH_HISTORY_ENTITY_KEY = 'authHistory';
export const AUTH_HISTORY_MODULE_AUTH_HISTORY_PASSWORD_HISTORY_ENTITY_KEY =
  'auth-history-password-history';
export const AUTH_HISTORY_MODULE_AUTH_HISTORY_PASSWORD_HISTORY_LIMIT_DAYS_DEFAULT =
  365 * 2;
