export const CRUD_MODULE_OPTIONS_TOKEN = 'CRUD_MODULE_OPTIONS_TOKEN';

export const CRUD_MODULE_SETTINGS_TOKEN = 'CRUD_MODULE_SETTINGS_TOKEN';

export const CRUD_MODULE_DEFAULT_SETTINGS_TOKEN =
  'CRUD_MODULE_DEFAULT_SETTINGS_TOKEN';

export const CRUD_MODULE_CRUD_REQUEST_KEY = 'CRUD_MODULE_CRUD_REQUEST_KEY';

export const CRUD_MODULE_CRUD_VALIDATION_KEY =
  'CRUD_MODULE_CRUD_VALIDATION_KEY';

export const CRUD_MODULE_CTRL_OPTIONS_METADATA =
  'CRUD_MODULE_CTRL_OPTIONS_METADATA';

export const CRUD_MODULE_ROUTE_ACTION_METADATA =
  'CRUD_MODULE_ROUTE_ACTION_METADATA';

export const CRUD_MODULE_ROUTE_CREATE_ONE_METADATA =
  'CRUD_MODULE_ROUTE_CREATE_ONE_METADATA';

export const CRUD_MODULE_ROUTE_UPDATE_ONE_METADATA =
  'CRUD_MODULE_ROUTE_UPDATE_ONE_METADATA';

export const CRUD_MODULE_ROUTE_DELETE_ONE_METADATA =
  'CRUD_MODULE_ROUTE_DELETE_ONE_METADATA';

export const CRUD_MODULE_ROUTE_REPLACE_ONE_METADATA =
  'CRUD_MODULE_ROUTE_REPLACE_ONE_METADATA';

export const CRUD_MODULE_ROUTE_RECOVER_ONE_METADATA =
  'CRUD_MODULE_ROUTE_RECOVER_ONE_METADATA';

export const CRUD_MODULE_ROUTE_VALIDATION_METADATA =
  'CRUD_MODULE_ROUTE_VALIDATION_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_METADATA';

export const CRUD_MODULE_ROUTE_MODEL_METADATA =
  'CRUD_MODULE_ROUTE_MODEL_METADATA';
