export const INVITATION_MODULE_SETTINGS_TOKEN =
  'INVITATION_MODULE_SETTINGS_TOKEN';

export const INVITATION_MODULE_DEFAULT_SETTINGS_TOKEN =
  'INVITATION_MODULE_DEFAULT_SETTINGS_TOKEN';

export const INVITATION_MODULE_SERVICE_TOKEN =
  'INVITATION_MODULE_SERVICE_TOKEN';

export const INVITATION_MODULE_OTP_SERVICE_TOKEN =
  'INVITATION_MODULE_OTP_SERVICE_TOKEN';

export const INVITATION_MODULE_EMAIL_SERVICE_TOKEN =
  'INVITATION_MODULE_EMAIL_SERVICE_TOKEN';

export const INVITATION_MODULE_USER_MODEL_SERVICE_TOKEN =
  'INVITATION_MODULE_USER_MODEL_SERVICE_TOKEN';

export const INVITATION_MODULE_INVITATION_ENTITY_KEY = 'invitation';
