export const INVITATION_MODULE_OPTIONS_TOKEN =
  'INVITATION_MODULE_OPTIONS_TOKEN';

export const INVITATION_MODULE_SETTINGS_TOKEN =
  'INVITATION_MODULE_SETTINGS_TOKEN';

export const INVITATION_MODULE_DEFAULT_SETTINGS_TOKEN =
  'INVITATION_MODULE_DEFAULT_SETTINGS_TOKEN';

export const INVITATION_MODULE_SERVICE_TOKEN =
  'INVITATION_MODULE_SERVICE_TOKEN';

export const INVITATION_MODULE_OTP_SERVICE_TOKEN =
  'INVITATION_MODULE_OTP_SERVICE_TOKEN';

export const INVITATION_MODULE_EMAIL_SERVICE_TOKEN =
  'INVITATION_MODULE_EMAIL_SERVICE_TOKEN';

export const INVITATION_MODULE_USER_LOOKUP_SERVICE_TOKEN =
  'INVITATION_MODULE_USER_LOOKUP_SERVICE_TOKEN';

export const INVITATION_MODULE_USER_MUTATE_SERVICE_TOKEN =
  'INVITATION_MODULE_USER_MUTATE_SERVICE_TOKEN';

export const INVITATION_MODULE_INVITATION_ENTITY_KEY = 'invitation';
