export const AUTH_GOOGLE_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_GOOGLE_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_GOOGLE_MODULE_SETTINGS_TOKEN =
  'AUTH_GOOGLE_MODULE_SETTINGS_TOKEN';

export const AUTH_GOOGLE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_GOOGLE_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_GOOGLE_STRATEGY_NAME = 'google';
