export const REFRESH_TOKEN_MODULE_OPTIONS_TOKEN =
  'REFRESH_TOKEN_MODULE_OPTIONS_TOKEN';

export const REFRESH_TOKEN_MODULE_SETTINGS_TOKEN =
  'REFRESH_TOKEN_MODULE_SETTINGS_TOKEN';

export const REFRESH_TOKEN_MODULE_DEFAULT_SETTINGS_TOKEN =
  'REFRESH_TOKEN_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_JWT_REFRESH_STRATEGY_NAME = 'AUTH_JWT_REFRESH_STRATEGY_NAME';

export const AUTH_REFRESH_LOOKUP_USER = 'AUTH_REFRESH_LOOKUP_USER';

export const AUTH_REFRESH_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_REFRESH_ISSUE_TOKEN_SERVICE_TOKEN';

//export const REFRESH_TOKEN_SERVICE_TOKEN = 'REFRESH_TOKEN_SERVICE_TOKEN';
