export const AUTH_REFRESH_MODULE_SETTINGS_TOKEN =
  'AUTH_REFRESH_MODULE_SETTINGS_TOKEN';

export const AUTH_REFRESH_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_REFRESH_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_REFRESH_MODULE_STRATEGY_NAME =
  'AUTH_REFRESH_MODULE_STRATEGY_NAME';

export const AuthRefreshVerifyService = Symbol(
  '__AUTH_REFRESH_MODULE_VERIFY_SERVICE_TOKEN__',
);

export const AuthRefreshIssueTokenService = Symbol(
  '__AUTH_REFRESH_MODULE_ISSUE_TOKEN_SERVICE_TOKEN__',
);

export const AuthRefreshUserModelService = Symbol(
  '__AUTH_REFRESH_MODULE_USER_MODEL_SERVICE_TOKEN__',
);
