export const SWAGGER_UI_MODULE_OPTIONS_TOKEN =
  'SWAGGER_UI_MODULE_OPTIONS_TOKEN';

export const SWAGGER_UI_MODULE_SETTINGS_TOKEN =
  'SWAGGER_UI_MODULE_SETTINGS_TOKEN';

export const SWAGGER_UI_DEFAULT_SETTINGS_TOKEN =
  'SWAGGER_UI_DEFAULT_SETTINGS_TOKEN';
