export const SWAGGER_UI_MODULE_SETTINGS_TOKEN =
  'SWAGGER_UI_MODULE_SETTINGS_TOKEN';

export const SWAGGER_UI_MODULE_DOCUMENT_BUILDER_TOKEN =
  'SWAGGER_UI_MODULE_DOCUMENT_BUILDER_TOKEN';

export const SWAGGER_UI_DEFAULT_SETTINGS_TOKEN =
  'SWAGGER_UI_DEFAULT_SETTINGS_TOKEN';
