export const FEDERATED_MODULE_SETTINGS_TOKEN =
  'FEDERATED_MODULE_SETTINGS_TOKEN';

export const FEDERATED_MODULE_DEFAULT_SETTINGS_TOKEN =
  'FEDERATED_MODULE_DEFAULT_SETTINGS_TOKEN';

export const FEDERATED_MODULE_USER_MODEL_SERVICE_TOKEN =
  'FEDERATED_MODULE_USER_MODEL_SERVICE_TOKEN';

export const FEDERATED_MODULE_FEDERATED_ENTITY_KEY = 'federated';
