export const FEDERATED_MODULE_OPTIONS_TOKEN = 'FEDERATED_MODULE_OPTIONS_TOKEN';

export const FEDERATED_MODULE_SETTINGS_TOKEN =
  'FEDERATED_MODULE_SETTINGS_TOKEN';

export const FEDERATED_MODULE_DEFAULT_SETTINGS_TOKEN =
  'FEDERATED_MODULE_DEFAULT_SETTINGS_TOKEN';

export const FEDERATED_MODULE_USER_LOOKUP_SERVICE_TOKEN =
  'FEDERATED_MODULE_USER_LOOKUP_SERVICE_TOKEN';

export const FEDERATED_MODULE_USER_MUTATE_SERVICE_TOKEN =
  'FEDERATED_MODULE_USER_MUTATE_SERVICE_TOKEN';

export const FEDERATED_MODULE_FEDERATED_ENTITY_REPO_TOKEN =
  'FEDERATED_MODULE_FEDERATED_ENTITY_REPO_TOKEN';

export const FEDERATED_MODULE_FEDERATED_CUSTOM_REPO_TOKEN =
  'FEDERATED_MODULE_FEDERATED_CUSTOM_REPO_TOKEN';
