export const AUTH_APPLE_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_APPLE_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_APPLE_MODULE_SETTINGS_TOKEN =
  'AUTH_APPLE_MODULE_SETTINGS_TOKEN';

export const AUTH_APPLE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_APPLE_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_APPLE_STRATEGY_NAME = 'apple';
