export const AUTH_APPLE_ISSUE_TOKEN_SERVICE_TOKEN =
  'AUTH_APPLE_ISSUE_TOKEN_SERVICE_TOKEN';

export const AUTH_APPLE_SERVICE_TOKEN = 'AUTH_APPLE_SERVICE_TOKEN';

export const AUTH_APPLE_MODULE_SETTINGS_TOKEN =
  'AUTH_APPLE_MODULE_SETTINGS_TOKEN';

export const AUTH_APPLE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_APPLE_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_APPLE_STRATEGY_NAME = 'apple';

export const AUTH_APPLE_VERIFY_ALGORITHM_RS256 = 'RS256';

export const AUTH_APPLE_TOKEN_ISSUER = 'https://appleid.apple.com';

export const AUTH_APPLE_JWT_KEYS = 'https://appleid.apple.com/auth/keys';
