export const USER_MODULE_OPTIONS_TOKEN = 'USER_MODULE_OPTIONS_TOKEN';
export const USER_MODULE_SETTINGS_TOKEN = 'USER_MODULE_SETTINGS_TOKEN';
export const USER_MODULE_DEFAULT_SETTINGS_TOKEN =
  'USER_MODULE_DEFAULT_SETTINGS_TOKEN';
export const USER_MODULE_USER_ENTITY_KEY = 'user';
export const USER_MODULE_USER_PASSWORD_HISTORY_ENTITY_KEY =
  'user-password-history';
export const USER_MODULE_USER_PASSWORD_HISTORY_LIMIT_DAYS_DEFAULT = 365 * 2;
