export const USER_MODULE_OPTIONS_TOKEN = 'USER_MODULE_OPTIONS_TOKEN';
export const USER_MODULE_SETTINGS_TOKEN = 'USER_MODULE_SETTINGS_TOKEN';
export const USER_MODULE_DEFAULT_SETTINGS_TOKEN =
  'USER_MODULE_DEFAULT_SETTINGS_TOKEN';
export const USER_MODULE_USER_ENTITY_REPO_TOKEN =
  'USER_MODULE_USER_ENTITY_REPO_TOKEN';
export const USER_MODULE_USER_CUSTOM_REPO_TOKEN =
  'USER_MODULE_USER_CUSTOM_REPO_TOKEN';
