export const FILE_MODULE_SETTINGS_TOKEN = 'FILE_MODULE_SETTINGS_TOKEN';

export const FILE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'FILE_MODULE_DEFAULT_SETTINGS_TOKEN';

export const FILE_MODULE_FILE_ENTITY_KEY = 'file';

export const FILE_STRATEGY_SERVICE_KEY = 'FILE_STRATEGY_SERVICE_KEY';
