import 'reflect-metadata';
import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  Controller,
  Get,
  Global,
  HttpCode,
  INestApplication,
  Module,
  UseGuards,
} from '@nestjs/common';
import request from 'supertest';
import {
  AuthPublic,
  RATE_LIMIT_STORE_TOKEN,
  RateLimit,
  RateLimitGuard,
  type RateLimitResult,
  type RateLimitStoreInterface,
} from '@concepta/rockets-core';
import { ApiOkResponse, ApiTags } from '@nestjs/swagger';

import {
  applyRocketsAuthE2eAppGlobals,
  createRocketsAuthStandardE2eTestingModule,
} from './helpers/rockets-auth-e2e-app.factory';

/**
 * A store the APP registers globally, competing with the one
 * `RocketsAuthRateLimitModule` provides. Every key it sees is a key the
 * auth registration did NOT get.
 */
class SpyStore implements RateLimitStoreInterface {
  readonly keys: string[] = [];
  async consume(
    key: string,
    limit: number,
    windowMs: number,
  ): Promise<RateLimitResult> {
    this.keys.push(key);
    return {
      allowed: true,
      limit,
      remaining: limit - 1,
      resetAt: Date.now() + windowMs,
    };
  }
}

const spy = new SpyStore();

@Global()
@Module({
  providers: [{ provide: RATE_LIMIT_STORE_TOKEN, useValue: spy }],
  exports: [RATE_LIMIT_STORE_TOKEN],
})
class CompetingStoreModule {}

@Controller('app-owned')
@ApiTags('Test')
@AuthPublic({ classLevel: true })
@UseGuards(RateLimitGuard)
class AppOwnedController {
  @Get()
  @HttpCode(200)
  @RateLimit({ limit: 100, windowMs: 60_000 })
  @ApiOkResponse({ description: 'App route, app store' })
  read(): string {
    return 'ok';
  }
}

async function boot(order: 'before' | 'after'): Promise<INestApplication> {
  const module = await createRocketsAuthStandardE2eTestingModule({
    mockEmailService: { sendMail: vi.fn().mockResolvedValue(undefined) },
    extraControllers: [AppOwnedController],
    ...(order === 'before'
      ? { importsBefore: [CompetingStoreModule] }
      : { importsAfter: [CompetingStoreModule] }),
  });
  const app = module.createNestApplication();
  applyRocketsAuthE2eAppGlobals(app);
  await app.init();
  return app;
}

/**
 * A guard resolves its dependencies from the injector of the module that
 * DECLARES the controller, so "the auth registration provides the token,
 * therefore auth routes use its store" is only true where auth declares
 * the controller or the declaring module imports the registration.
 *
 * `/signup` is deliberately NOT covered here: its controller is
 * generated by `CrudModule.forFeature`, which takes neither `imports` nor
 * `providers`, so nothing can give that module a local store and it
 * resolves the global registry — where the FIRST registration wins.
 * CONFIGURATION.md §7b states that boundary; do not pin it here as if it
 * were the intended behaviour.
 */
describe('auth rate-limit store resolution (e2e)', () => {
  let app: INestApplication | undefined;

  afterEach(async () => {
    await app?.close();
    app = undefined;
    spy.keys.length = 0;
  });

  it.each(['before', 'after'] as const)(
    'auth routes never reach a competing global store (registered %s)',
    async (order) => {
      app = await boot(order);

      // Proves the competing store IS wired: the app's own route uses it.
      await request(app.getHttpServer()).get('/app-owned').expect(200);
      expect(spy.keys.length).toBeGreaterThan(0);
      const appRouteKeys = spy.keys.length;

      // Declared by the auth module itself.
      await request(app.getHttpServer())
        .post('/token/password')
        .send({ username: 'nobody', password: 'whatever-123' });

      // Declared by the invitation-acceptance module, which imports the
      // auth rate-limit registration for exactly this reason.
      await request(app.getHttpServer())
        .patch('/invitation-acceptance/some-code')
        .send({ passcode: 'nope' });

      expect(spy.keys).toHaveLength(appRouteKeys);
    },
  );
});
