export const ACCESS_CONTROL_MODULE_OPTIONS_TOKEN =
  'ACCESS_CONTROL_MODULE_OPTIONS_TOKEN';
export const ACCESS_CONTROL_MODULE_SETTINGS_TOKEN =
  'ACCESS_CONTROL_MODULE_SETTINGS_TOKEN';
export const ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ACCESS_CONTROL_MODULE_CTLR_METADATA =
  'ACCESS_CONTROL_MODULE_CTLR_METADATA';
export const ACCESS_CONTROL_MODULE_GRANT_METADATA =
  'ACCESS_CONTROL_MODULE_GRANT_METADATA';
export const ACCESS_CONTROL_MODULE_FILTERS_METADATA =
  'ACCESS_CONTROL_MODULE_FILTERS_METADATA';
