export const ACCESS_CONTROL_OPTIONS_KEY = 'ACCESS_CONTROL_OPTIONS';
export const ACCESS_CONTROL_CTLR_CONFIG_KEY = 'ACCESS_CONTROL_CTLR';
export const ACCESS_CONTROL_GRANT_CONFIG_KEY = 'ACCESS_CONTROL_GRANTS';
export const ACCESS_CONTROL_FILTERS_CONFIG_KEY = 'ACCESS_CONTROL_FILTERS';
