import {
  ACCESS_CONTROL_MODULE_OPTIONS_TOKEN,
  ACCESS_CONTROL_MODULE_SETTINGS_TOKEN,
  ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN,
  ACCESS_CONTROL_MODULE_CTLR_METADATA,
  ACCESS_CONTROL_MODULE_FILTERS_METADATA,
  ACCESS_CONTROL_MODULE_GRANT_METADATA,
} from './constants';

describe('Constants', () => {
  it('Should each match expected value', () => {
    expect(ACCESS_CONTROL_MODULE_OPTIONS_TOKEN).toEqual(
      'ACCESS_CONTROL_MODULE_OPTIONS_TOKEN',
    );
    expect(ACCESS_CONTROL_MODULE_SETTINGS_TOKEN).toEqual(
      'ACCESS_CONTROL_MODULE_SETTINGS_TOKEN',
    );
    expect(ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN).toEqual(
      'ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN',
    );
    expect(ACCESS_CONTROL_MODULE_CTLR_METADATA).toEqual(
      'ACCESS_CONTROL_MODULE_CTLR_METADATA',
    );
    expect(ACCESS_CONTROL_MODULE_FILTERS_METADATA).toEqual(
      'ACCESS_CONTROL_MODULE_FILTERS_METADATA',
    );
    expect(ACCESS_CONTROL_MODULE_GRANT_METADATA).toEqual(
      'ACCESS_CONTROL_MODULE_GRANT_METADATA',
    );
  });
});
