export const PASSWORD_MODULE_SETTINGS_TOKEN = 'PASSWORD_MODULE_SETTINGS_TOKEN';
export const PASSWORD_MODULE_DEFAULT_SETTINGS_TOKEN =
  'PASSWORD_MODULE_DEFAULT_SETTINGS_TOKEN';
export const PASSWORD_STORAGE_SERVICE_TOKEN = 'PASSWORD_STORAGE_SERVICE_TOKEN';
