export const REFRESH_TOKEN_MODULE_OPTIONS_TOKEN = 'REFRESH_TOKEN_MODULE_OPTIONS_TOKEN';

export const REFRESH_TOKEN_MODULE_SETTINGS_TOKEN = 'REFRESH_TOKEN_MODULE_SETTINGS_TOKEN';

export const REFRESH_TOKEN_MODULE_DEFAULT_SETTINGS_TOKEN =
  'REFRESH_TOKEN_MODULE_DEFAULT_SETTINGS_TOKEN';

export const REFRESH_TOKEN_SERVICE_TOKEN = 'REFRESH_TOKEN_SERVICE_TOKEN';

