export const ROLE_MODULE_OPTIONS_TOKEN = 'ROLE_MODULE_OPTIONS_TOKEN';
export const ROLE_MODULE_SETTINGS_TOKEN = 'ROLE_MODULE_SETTINGS_TOKEN';
export const ROLE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ROLE_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ROLE_MODULE_ORG_ENTITY_KEY = 'role';
