export const ROLE_MODULE_OPTIONS_TOKEN = 'ROLE_MODULE_OPTIONS_TOKEN';
export const ROLE_MODULE_SETTINGS_TOKEN = 'ROLE_MODULE_SETTINGS_TOKEN';
export const ALL_ROLES_REPOSITORIES_TOKEN = 'ALL_ROLES_REPOSITORIES_TOKEN';
export const ROLE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ROLE_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ROLE_MODULE_ORG_ENTITY_KEY = 'role';
export const USER_ROLE_MODULE_ORG_ENTITY_KEY = 'userRole';
export const API_KEY_ROLE_MODULE_ORG_ENTITY_KEY = 'apiKeyRole';
export const ORG_MEMBER_ROLE_MODULE_ORG_ENTITY_KEY = 'orgMemberRole';
