export const ROLE_MODULE_OPTIONS_TOKEN = 'ROLE_MODULE_OPTIONS_TOKEN';
export const ROLE_MODULE_SETTINGS_TOKEN = 'ROLE_MODULE_SETTINGS_TOKEN';
export const ROLE_MODULE_REPOSITORIES_TOKEN = 'ROLE_MODULE_REPOSITORIES_TOKEN';
export const ROLE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ROLE_MODULE_DEFAULT_SETTINGS_TOKEN';
export const ROLE_MODULE_ROLE_ENTITY_KEY = 'role';
export const ROLE_MODULE_ROLE_ASSIGNMENT_KEY = 'roleAssignments';
