export const OTP_MODULE_SETTINGS_TOKEN = 'OTP_MODULE_SETTINGS_TOKEN';
export const OTP_MODULE_REPOSITORIES_TOKEN = 'OTP_MODULE_REPOSITORIES_TOKEN';
export const OTP_MODULE_DEFAULT_SETTINGS_TOKEN =
  'OTP_MODULE_DEFAULT_SETTINGS_TOKEN';
