export const OTP_MODULE_OPTIONS_TOKEN = 'OTP_MODULE_OPTIONS_TOKEN';
export const OTP_MODULE_SETTINGS_TOKEN = 'OTP_MODULE_SETTINGS_TOKEN';
export const OTP_MODULE_REPOSITORIES_TOKEN = 'OTP_MODULE_REPOSITORIES_TOKEN';
export const OTP_MODULE_DEFAULT_SETTINGS_TOKEN =
  'OTP_MODULE_DEFAULT_SETTINGS_TOKEN';
export const OTP_MODULE_OTP_ENTITY_KEY = 'otp';
