export const PHOTO_MODULE_OPTIONS_TOKEN = 'PHOTO_MODULE_OPTIONS_TOKEN';
export const PHOTO_MODULE_ENTITY_REPO_TOKEN = 'PHOTO_MODULE_ENTITY_REPO_TOKEN';
export const PHOTO_MODULE_CUSTOM_REPO_TOKEN = 'PHOTO_MODULE_CUSTOM_REPO_TOKEN';
