export const REPORT_MODULE_SETTINGS_TOKEN = 'REPORT_MODULE_SETTINGS_TOKEN';

export const REPORT_MODULE_DEFAULT_SETTINGS_TOKEN =
  'REPORT_MODULE_DEFAULT_SETTINGS_TOKEN';

export const REPORT_MODULE_REPORT_ENTITY_KEY = 'report';

export const REPORT_STRATEGY_SERVICE_KEY = 'REPORT_STRATEGY_SERVICE_KEY';
