export const AUTH_JWT_MODULE_SETTINGS_TOKEN = 'AUTH_JWT_MODULE_SETTINGS_TOKEN';

export const AUTH_JWT_STRATEGY_NAME = 'jwt';

export const AUTH_JWT_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_JWT_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AuthJwtVerifyTokenService = Symbol(
  '__AUTH_JWT_MODULE_VERIFY_TOKEN_SERVICE_TOKEN__',
);

export const AuthJwtUserLookupService = Symbol(
  '__AUTH_JWT_MODULE_USER_LOOKUP_SERVICE_TOKEN__',
);
