export const AUTH_JWT_MODULE_OPTIONS_TOKEN = 'AUTH_JWT_MODULE_OPTIONS_TOKEN';

export const AUTH_JWT_MODULE_SETTINGS_TOKEN = 'AUTH_JWT_MODULE_SETTINGS_TOKEN';

export const AUTH_JWT_MODULE_DEFAULT_SETTINGS_TOKEN =
  'AUTH_JWT_MODULE_DEFAULT_SETTINGS_TOKEN';

export const AUTH_JWT_STRATEGY_NAME = 'jwt';
